export const PRICE_IDS = {
  STRIPE_MONTHLY_PLUS_PRICE_ID: process.env.STRIPE_MONTHLY_PLUS_PRICE_ID,
  STRIPE_MONTHLY_ULTRA_PRICE_ID: process.env.STRIPE_MONTHLY_ULTRA_PRICE_ID,
}

export const STRIPE_API_VERSION = '2022-11-15'
